name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - poppler: poppler-0.35.0 # oldest supported release
          exiv2: exiv2-0.21
          os: ubuntu-18.04
        - poppler: poppler-0.48.0 # Debian 9 "Stretch"
          exiv2: exiv2-0.25
          os: ubuntu-18.04
        - poppler: poppler-0.62.0 # Ubuntu 18.04 LTS "Bionic Beaver"
          exiv2: exiv2-0.25
          os: ubuntu-18.04
        - poppler: poppler-0.71.0 # Debian 10 "Buster"
          exiv2: exiv2-0.25
          os: ubuntu-20.04
        - poppler: poppler-0.86.1 # Ubuntu 20.04 LTS "Focal Fossa"
          exiv2: exiv2-0.27.2
          os: ubuntu-20.04
        - poppler: poppler-20.09.0 # Debian 11 "Bullseye"
          exiv2: exiv2-0.27.3
          os: ubuntu-20.04
        - poppler: poppler-22.02.0 # Ubuntu 22.04 LTS "Jammy Jellyfish"
          exiv2: exiv2-0.27.5
          os: ubuntu-22.04
        - poppler: poppler-22.03.0 # newest tested release
          exiv2: exiv2-0.27.5
          os: ubuntu-20.04
          cppcheck: cppcheck
          docs: docs
        - poppler: poppler-git
          exiv2: exiv2-git
          os: ubuntu-20.04
          cc: clang
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-${{matrix.os}}-${{matrix.cc || 'gcc'}}-${{matrix.poppler}}-${{matrix.exiv2}}
    - name: add /usr/lib/ccache to $PATH
      run: |
        echo "/usr/lib/ccache:$PATH" >> $GITHUB_PATH
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install deps
      run:
        sudo apt-get install
          autoconf
          automake
          ccache
          cppcheck
          djvulibre-bin
          docbook-xml
          docbook-xsl
          fonts-linuxlibertine
          gettext
          libdjvulibre-dev
          libfontconfig1-dev
          libgraphicsmagick++1-dev
          libopenjp2-7-dev
          libxml2-utils
          locales-all
          pkg-config
          texlive-fonts-recommended
          texlive-luatex
          uuid-dev
          xsltproc
    - name: set up C++ compiler
      run: |
        CC=${{matrix.cc || 'gcc'}}
        echo CC=$CC >> $GITHUB_ENV
        CXX=${{(matrix.cc && format('{0}++', matrix.cc)) || 'g++'}}
        echo CXX=$CXX >> $GITHUB_ENV
    - name: download and unpack Poppler source tarball
      run: |
        wget https://poppler.freedesktop.org/${{matrix.poppler}}.tar.xz
        tar -xvvf poppler-*.tar.*
      if: matrix.poppler != 'poppler-git'
    - name: clone Poppler git repo
      run:
        git clone https://anongit.freedesktop.org/git/poppler/poppler.git poppler-git
      if: matrix.poppler == 'poppler-git'
    - name: configure Poppler
      run: |
        cd poppler-*/
        cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_XPDF_HEADERS=ON -DENABLE_UNSTABLE_API_ABI_HEADERS=ON -DBUILD_GTK_TESTS=OFF -DBUILD_QT4_TESTS=OFF -DBUILD_QT5_TESTS=OFF -DBUILD_QT6_TESTS=OFF -DBUILD_CPP_TESTS=OFF -DBUILD_MANUAL_TESTS=OFF -DENABLE_SPLASH=ON -DENABLE_UTILS=OFF -DENABLE_CPP=OFF -DENABLE_GLIB=OFF -DENABLE_QT4=OFF -DENABLE_QT5=OFF -DENABLE_QT6=OFF -DENABLE_LIBCURL=OFF -DENABLE_ZLIB=OFF -DENABLE_BOOST=OFF
    - name: build and install Poppler
      run: |
        cd poppler-*/
        make
        make install
        echo CPATH=~/.local/include/ >> $GITHUB_ENV
        echo PKG_CONFIG_PATH=~/.local/lib/pkgconfig/ >> $GITHUB_ENV
        echo LD_LIBRARY_PATH=~/.local/lib/ >> $GITHUB_ENV
        CXXFLAGS='-g -O2'
        if grep -rwm1 std::optional .;
        then
          CXXFLAGS+=' -std=gnu++17'
        fi
        echo "CXXFLAGS=$CXXFLAGS" | tee -a $GITHUB_ENV;
    - name: remove Poppler source
      run:
        rm -rf poppler-*
    - name: download and unpack Exiv2 source tarball
      run: |
        v=${{matrix.exiv2}}
        v=${v#exiv2-}
        case $v in
          0.2[0-6]) s='';;
          *) s='-Source';;
        esac
        wget "https://github.com/Exiv2/exiv2/releases/download/v${v}/exiv2-${v}${s}.tar.gz"
        tar -xvvf exiv2-*.tar.*
      if: matrix.exiv2 != 'exiv2-git'
    - name: clone Exiv2 git repo
      run: |
        git clone https://github.com/Exiv2/exiv2 exiv2-git
      if: matrix.exiv2 == 'exiv2-git'
    - name: configure Exiv2
      run: |
        cd exiv2-*/
        case ${{matrix.exiv2}} in
          exiv2-0.2[0-6]) ./configure --prefix ~/.local --disable-static --without-zlib --disable-lensdata --disable-nls || cat config.log /fail;;
          *) cmake . -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_VERBOSE_MAKEFILE=ON -DEXIV2_ENABLE_PNG=OFF -DEXIV2_ENABLE_NLS=OFF -DEXIV2_ENABLE_PRINTUCS2=OFF -DEXIV2_ENABLE_LENSDATA=OFF -DEXIV2_BUILD_EXIV2_COMMAND=OFF -DEXIV2_BUILD_SAMPLES=OFF;;
        esac
    - name: build and install Exiv2
      run: |
        cd exiv2-*/
        find . -name 'exiv2.hpp' | xargs sed -i -e '/"pngimage[.]hpp"/d'  # https://dev.exiv2.org/issues/1103
        make
        make install
    - name: remove Exiv2 source
      run:
        rm -rf exiv2-*
    - name: check the changelog
      run:
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
    - name: generate autotools stuff
      run:
        private/autogen
    - name: configure
      run: |
        CXXFLAGS+=' -Werror=switch-enum'
        ./configure --prefix ~/.local $configure_options || cat config.log /fail
    - name: build
      run:
        make
    - name: smoke test
      run:
        ./pdf2djvu --version
    - name: set up Python
      run: |
        sudo apt-get install python2
        sudo ln -sf python2 /usr/bin/python
        python --version
      if: matrix.os != 'ubuntu-18.04'
    - name: install Python deps
      run: |
        sudo apt-get install python-nose python-pil
      if: matrix.os != 'ubuntu-22.04'
    - name: install Python deps
      run: |
        sudo apt-get install python-pip
        python -m pip install nose
        python -m pip install Pillow
      if: matrix.os == 'ubuntu-22.04'
    - name: run tests
      run: |
        make -C tests prepare
        make test
    - name: build docs
      run: |
        make -C doc
      if: matrix.docs
    - name: install
      run:
        make install
    - name: check whether the executable was installed correctly
      run: |
        cd /
        pdf2djvu --version
    - name: check whether the man page was installed correctly
      run: |
        cd /
        man 1 pdf2djvu | grep -A 10 -w PDF2DJVU
      env:
        MANPATH: /home/runner/.local/share/man
        MANWIDTH: 80
      if: matrix.docs
    - name: run cppcheck
      run:
        cppcheck --error-exitcode=1 *.cc
      if: matrix.cppcheck
    - name: check docs
      run: |
        sudo apt-get install python-docutils
        private/check-rst
        make -C doc check
      if: matrix.docs
  Python:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        cd tests
        python -m pydiatra -v .
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        cd tests
        python -m pyflakes .
    - name: pip install deps
      run: |
        python -m pip install nose
        python -m pip install Pillow
    - name: run pylint
      run: |
        python -m pip install 'lazy-object-proxy<1.7.0' pylint
        cd tests
        python -m pylint *.py

# vim:ts=2 sts=2 sw=2 et
